### ISSUE TITLE
Interface Index

### ISSUE THREAD

**Issue by tr3ysmith** [EstebanBorai/network-interface#11]
Would it be possible to add the interface index to the struct too?

I know libc has several function calls to get that information: https://man7.org/linux/man-pages/man3/if_nametoindex.3.html

Mainly this would be helpful when dealing with ipv6 multicast membership because the `join_multicast_v6()` on Rust's `UdpSocket` requires an interface number to bind to:

https://doc.rust-lang.org/stable/std/net/struct.UdpSocket.html#method.join_multicast_v6

**Comment by EstebanBorai** [comment]
Hi @tr3ysmith! Thanks so much for this feature request.
If you feel like working on this, please don't hesitate on opening a PR, I'm glad to help.

As you have been suggesting relevant feature requests, I was thinking on tweaking a bit the crate architecture to be able to provide as much support as I'm able to do without delaying releases. Here's a discussion #12 where your input would be appreciated.

Thanks in advance! Keep up the feature requests!

**Comment by EstebanBorai** [comment]
Closing given that is added on #25!
