### ISSUE TITLE
addr

### ISSUE THREAD

**Issue by xHyroM** [EstebanBorai/network-interface#13]
How can i use `addr` in my project?
```rust
pub fn network_interfaces() -> Vec<NetworkInfo> {
    let mut all_network_interfaces = Vec::new();

    for network in network_interface::NetworkInterface::show().unwrap().iter() {
        all_network_interfaces.push(NetworkInfo {
            name: network.name.to_string(),
            address: network.addr.unwrap().ip, // i want to return ip
        })
    }

    all_network_interfaces
}
```

**Comment by EstebanBorai** [comment]
Hi @xHyroM! Thanks so much for opening this issue.

I'm glad to help you with your requirement, it would be great if we can have this question in a GitHub Discussion, can you help me moving this issue there?

Discussions are great for Q&A threads like this, I think moving it there would help building a knowledge base for this crate where anyone could reach for help.

Here is the link to the Discussions section for this repo so you don't have to click more than once to get there 😄:
https://github.com/EstebanBorai/network-interface/discussions/new

Thanks in advance!

**Comment by xHyroM** [comment]
> Hi @xHyroM! Thanks so much for opening this issue.
> 
> I'm glad to help you with your requirement, it would be great if we can have this question in a GitHub Discussion, can you help me moving this issue there?
> 
> Discussions are great for Q&A threads like this, I think moving it there would help building a knowledge base for this crate where anyone could reach for help.
> 
> Here is the link to the Discussions section for this repo so you don't have to click more than once to get there 😄: https://github.com/EstebanBorai/network-interface/discussions/new
> 
> Thanks in advance!

https://github.com/EstebanBorai/network-interface/discussions/14
