### ISSUE TITLE
Can't build on android

### ISSUE THREAD

**Issue by xHyroM** [EstebanBorai/network-interface#15]
Workflows:
https://github.com/xHyroM/bun-utilities/runs/7654022255?check_suite_focus=true
https://github.com/xHyroM/bun-utilities/runs/7654022421?check_suite_focus=true

code:
```rust
use network_interface::{Addr, NetworkInterfaceConfig};

pub struct NetworkInfo {
    pub name: String,
    pub address: String,
    pub netmask: Option<String>,
    pub family: String,
}

pub unsafe fn network_interfaces() -> Vec<NetworkInfo> {
    let all_network_interfaces = network_interface::NetworkInterface::show().unwrap();
    let ifaces = all_network_interfaces.iter().filter_map(|net| {
        if let Some(net_addr) = net.addr {
            let address: String = match net_addr {
                Addr::V4(ip_addr) => ip_addr.ip.to_string(),
                Addr::V6(ip_addr) => ip_addr.ip.to_string(),
            };

            let netmask: String = match net_addr {
                Addr::V4(ip_addr) => ip_addr.netmask.unwrap_unchecked().to_string(),
                Addr::V6(ip_addr) => ip_addr.netmask.unwrap_unchecked().to_string(),
            };

            let family: String = match net_addr {
                Addr::V4(..) => "IPv4".to_string(),
                Addr::V6(..) => "IPv6".to_string(),
            };

            return Some(NetworkInfo {
                name: net.name.clone(),
                address,
                netmask: Some(netmask),
                family,
            });
        }

        None
    }).collect::<Vec<NetworkInfo>>();

    ifaces
}
```

**Comment by EstebanBorai** [comment]
Hi @xHyroM!

Im finding your issue interesting, as of today this crate supports: macOS, Linux and Windows. It would be awesome to also provide support for Android.

Can you point me on the right direction on how you are running Rust on Android? That would be helpful.

Thanks in advance!

**Comment by xHyroM** [comment]
> Hi @xHyroM!
> 
> Im finding your issue interesting, as of today this crate supports: macOS, Linux and Windows. It would be awesome to also provide support for Android.
> 
> Can you point me on the right direction on how you are running Rust on Android? That would be helpful.
> 
> Thanks in advance!

I'm using napi workflow, https://github.com/xHyroM/bun-utilities/blob/32edf3f0f564513c30cfe49b6ffff32d7bfce898/.github/workflows/CI.yml#L88

**Comment by xHyroM** [comment]
Also, could you add support for freebsd?

**Comment by EstebanBorai** [comment]
> Also, could you add support for freebsd?

Hi @xHyroM! This is a great idea!
As of today I'm able to provide support for Linux, macOS and Windows. But Im looking into support more platforms as I find time.

I can use some help to provide support sooner! If you are willing to help please don't hesitate to open PRs or issues!

**Comment by ahcodedthat** [comment]
[The `nix` crate has a portable safe wrapper for `getifaddrs`.](https://docs.rs/nix/0.25.0/nix/ifaddrs/index.html) It might be a good idea to use that on every platform where it's available.

**Comment by EstebanBorai** [comment]
> [The `nix` crate has a portable safe wrapper for `getifaddrs`.](https://docs.rs/nix/0.25.0/nix/ifaddrs/index.html) It might be a good idea to use that on every platform where it's available.

SGTM! Will give it a shot during the week, thanks for sharing!
