### ISSUE TITLE
Add support for serde

### ISSUE THREAD

**Issue by Tudyx** [EstebanBorai/network-interface#19]
In can be cool to add `serde` under a feature flag and provide [`Serialize`](https://docs.rs/serde/latest/serde/trait.Serialize.html) / [`Deserialize`](https://docs.rs/serde/latest/serde/trait.Deserialize.html) for comon type such as 

- `NetworkInterface`
- `Addr`
- `V4IfAddr`
- `V6IfAddr`

I'm a little busy right now, but in couple of week maybe i will have some times to tackle this myself

**Comment by EstebanBorai** [comment]
Hi @Tudyx!

Sounds great in my opinion! As this is not an urgent feature I can wait for you if you want to work on this.
Otherwise let me know and I will be happy to work on it.

Thanks for opening this issue!

**Comment by EstebanBorai** [comment]
Hi @Tudyx, this morning I had some time to address this feature request and opened this PR: https://github.com/EstebanBorai/network-interface/pull/20

I would love to get some feedback from you.
Thanks in advance.

**Comment by Tudyx** [comment]
Hi @EstebanBorai, thank you for finding the time to address this. I've left you some feedback in the PR #20

**Comment by EstebanBorai** [comment]
Hi @Tudyx!

I have been very busy and haven't found enough time to finish the PR on #20 which lacks of Deserialization support.
If you consider you want to give it a shot just go ahead!

**Comment by EstebanBorai** [comment]
Already supports serde with macros, for alternative approach PRs are welcome!
