### ISSUE TITLE
Network interfaces can have more than one IP address

### ISSUE THREAD

**Issue by WilliamVenner** [EstebanBorai/network-interface#26]
I noticed my WiFi network interface only returns its IPv6 address in this library. In reality, I have both an IPv4 and IPv6 address, so the library should return both.

**Comment by RReverser** [comment]
This already works, it just returns both as separate `NetworkInterface` objects, each with own address but with the same name and index.

**Comment by EstebanBorai** [comment]
Oh yes! Thanks for participating @RReverser! I will close this as completed then!
