### ISSUE TITLE
linux mac address is none

### ISSUE THREAD

**Issue by CarbonPool** [EstebanBorai/network-interface#27]

**Comment by EstebanBorai** [comment]
Hi @CarbonPool! You are right! I will be drafting a new version today with these changes which will resolve this issue:

https://github.com/EstebanBorai/network-interface/commit/bb5527352ae9e694afd50a09a7cea5b85e0d8604

Thanks for reporting!

**Comment by EstebanBorai** [comment]
Hi @CarbonPool!

Sorry for the delay, has been busy days!
The version with support for MAC Address for Linux is out!

https://github.com/EstebanBorai/network-interface/compare/v0.1.5...v0.1.6
