### ISSUE TITLE
Migrate `winapi` to `windows-rs`?

### ISSUE THREAD

**Issue by mokeyish** [EstebanBorai/network-interface#29]
[windows-rs ](https://github.com/microsoft/windows-rs) seems more active than [winapi](https://github.com/retep998/winapi-rs), and it is maintained by Microsoft. 

> The [windows](https://crates.io/crates/windows) and [windows-sys](https://crates.io/crates/windows-sys) crates let you call any Windows API past, present, and future using code generated on the fly directly from the [metadata describing the API](https://github.com/microsoft/windows-rs/tree/master/crates/libs/metadata/default) and right into your Rust package where you can call them as if they were just another Rust module.

**Comment by EstebanBorai** [comment]
Hi @mokeyish! Thanks for your interest on this crate.

We used to depend on Windows crate but we moved to winapi due to cross-compilation issues. I havent took the time to review it again.

Here is the PR if you are interested:
https://github.com/EstebanBorai/network-interface/pull/9

**Comment by EstebanBorai** [comment]
Please feel free to reopen if you consider it necessary!
