### ISSUE TITLE
Free allocated memory by using `freeidaddrs`

### ISSUE THREAD

**Issue by CandySunPlus** [EstebanBorai/network-interface#31]
The `addr` in `NetworkInterface::show` is not freed after use, which can lead to memory leaks?
https://github.com/EstebanBorai/network-interface/blob/main/src/target/linux.rs#L21
https://github.com/EstebanBorai/network-interface/blob/main/src/target/macos/mod.rs#L22

you need call `libc::freeidaddrs(*addr)` before return the `network_interfaces`

**Comment by EstebanBorai** [comment]
Hi @CandySunPlus! Thanks for opening this issue.

You are right, we could improve memory usage by explicitly releasing memory allocated imperatively.

I will take a look into this in the next hours, feel free to open a PR if you feel like working on this.

Have a great week! Keep you tuned!

**Comment by CandySunPlus** [comment]
There were some issues with `IfAddrIterator` handling in the previous commit, which are fixed in this PR.
https://github.com/EstebanBorai/network-interface/pull/33
@EstebanBorai

**Comment by EstebanBorai** [comment]
@CandySunPlus thanks for your dedication on this PRs!
Will close this issue given that improvements addressed the bug reported here.
Feel free to reopen o create a new one if required.
