### ISSUE TITLE
`broadcast` should probably return `Option<Ipv4Addr>`

### ISSUE THREAD

**Issue by RReverser** [EstebanBorai/network-interface#37]
There is no concept of broadcast in IPv6, so I don't think it makes sense to return the `IpAddr` enum in the `broadcast()` method.

**Comment by EstebanBorai** [comment]
Hi @RReverser! Thanks for opening this issue!

I agree, I think we could just go with the proposal approach in this issue which would be having the `broadcast` method return `Option<Ipv4Addr>` if I'm not mistaken!

Please let me know if you are willing to work on this and open a PR!

I don't think is a big deal to draft a major release if this improvement is introduced!

Thanks in advance!

**Comment by RReverser** [comment]
Thanks, but I found few more minor limitations for my usecase that are addressed in [`default-net`](https://docs.rs/default-net) instead, so going to go with that one for now. Just figured I'd open an issue anyway.
