### ISSUE TITLE
Can you add a gateway field?

### ISSUE THREAD

**Issue by qxqxq** [EstebanBorai/network-interface#4]
Can you add a gateway field?

**Comment by EstebanBorai** [comment]
Hi @qxqxq, thanks for opening this issue!

It would help me to understand better the feature you are requesting by having a bit of context. Can I have a description on what you want to achieve? Which Operative System are you using? Perhaps you want to refer to [Windows IP Adapter Gateway Addresses](https://docs.microsoft.com/en-us/windows/win32/api/iptypes/ns-iptypes-ip_adapter_gateway_address_lh)?

**Comment by tr3ysmith** [comment]
@qxqxq they're using libc to grab the ip information on linux and mac, and I know that specifically that call they're using doesn't retrieve this information. I have a similar need on my application and for linux, I parse the ip route table `ip r`

if you want to build your own command use this:
`ip r | grep {nic} | grep default | cut -d ' ' -f 3  | head -n1`
replace nic with the name of the interface you want the gateway of. You could code this into a system command easily.

hope that helps!
