### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by surban** [EstebanBorai/network-interface#49]
I am using network-interface in [Aggligator](https://github.com/surban/aggligator/) and have received [a request](https://github.com/surban/aggligator/issues/6) to support FreeBSD. The only issue seems to be that it is currently unsupported by network-interface.

Thus FreeBSD support would be greatly appreciated.

**Comment by EstebanBorai** [comment]
Hi @surban!

I see, I think we can have the same approach as on Local IP Address? You can check out this PR https://github.com/EstebanBorai/local-ip-address/pull/95.

Let me know any questions!
