### ISSUE TITLE
Add MAC Address to interface struct

### ISSUE THREAD

**Issue by tr3ysmith** [EstebanBorai/network-interface#7]
I know this would require a different lookup in libc, but having the MAC hardware address included would be super helpful. 

As I understand it, you have to call `ioctl` with this flag`SIOCGIFHWADDR`. I'm not very savvy with Rust and libc yet, but figured I'd ask!

**Comment by EstebanBorai** [comment]
Hi @tr3ysmith! Thanks so much for opening this feature request!

Thanks for pointing out an approach as well, is very appreciated. This crate attempts to provide the same features under the same API for Window, Linux and macOS. This means that the feature should be supported on the three environments.

I will dig into a Windows implementation as well to make sure we have all targets supported. Thanks again!

**Comment by EstebanBorai** [comment]
Hi @tr3ysmith I replaced the implementation on #8 with a new one in #10.
This time Im using FFI to consume the `LLADDR` function to retrieve the MAC Address.

If you have any early feedback that would be awesome, thanks in advance!

**Comment by tr3ysmith** [comment]
@EstebanBorai Thanks so much! I'll give it a shot this week!! This is awesome!

**Comment by EstebanBorai** [comment]
@tr3ysmith thanks for your patience and time, I have updated the approach and also introduced the field for `macOS` I still have to work on providing support for Windows and Linux. If you have any input I'm glad to hear!

**Comment by EstebanBorai** [comment]
Hi @tr3ysmith!

Just wanted to share that support for MAC Addresses is now available for Linux and Macintosh!
We still have to work on providing support to Windows anytime soon!

Keep you updated!

**Comment by joaoantoniocardoso** [comment]
Hello!

The available MAC address is (probably, I didn't check) the **current**, right? Which can [easily](https://wiki.archlinux.org/title/MAC_address_spoofing) be changed.

Could we also add the **permanent** one? Here's how [ethtool](https://kernel.googlesource.com/pub/scm/network/ethtool/ethtool/+/refs/heads/ethtool-3.4.y/ethtool.c#3076) and [macchanger](https://github.com/alobbs/macchanger/blob/master/src/netinfo.c#L102) get the permanent MAC address.

Thanks!

**Comment by EstebanBorai** [comment]
> Hello!
> 
> The available MAC address is (probably, I didn't check) the **current**, which can [easily](https://wiki.archlinux.org/title/MAC_address_spoofing) be changed, right?
> 
> Could we also add the **permanent** one? Here's how [ethtool](https://kernel.googlesource.com/pub/scm/network/ethtool/ethtool/+/refs/heads/ethtool-3.4.y/ethtool.c#3076) and [macchanger](https://github.com/alobbs/macchanger/blob/master/src/netinfo.c#L102) get the permanent MAC address.
> 
> Thanks!

Hi @joaoantoniocardoso!

Makes sense to me! Would you like to work on this?

**Comment by EstebanBorai** [comment]
Closing due to stale
